### ISSUE TITLE
`apt upgrade` overwrites package installed by Pacstall

### ISSUE THREAD

**Issue by Henryws** [pacstall/pacstall#423]
**Describe the bug**
When installing a package from Pacstall, such as `neovim`, the dummy deb is created, but apt believes this to be outdated and proceeds to try to upgrade it from apt, therefore overwriting the Pacstall version

**To Reproduce**
Install Pacstall
Install a package, like `neovim`
Upgrade with apt
Observe that apt wants to upgrade `neovim`

**Expected behavior**
For the dummy deb to not upgrade, perhaps by pinning it

**Desktop (please complete the following information):**

- OS + version: Debian Sid
- Pacstall Version + branch: 1.7 Develop

**Comment by wizard-28** [comment]
Here's an example from `cmatrix`
```yaml
❯ apt show cmatrix -a
Package: cmatrix
Version: 2.0-2
Priority: optional
Section: universe/misc
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Boyuan Yang <byang@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 52.2 kB
Depends: libc6 (>= 2.4), libncurses6 (>= 6), libtinfo6 (>= 6)
Recommends: kbd
Suggests: cmatrix-xfont
Homepage: https://github.com/abishekvashok/cmatrix
Download-Size: 17.2 kB
APT-Sources: mirror://mirrors.ubuntu.com/mirrors.txt focal/universe amd64 Packages
Description: simulates the display from "The Matrix"
 Screen saver for the terminal based in the movie "The Matrix". It works in
 terminals of all dimensions and have the following features:
  * Support terminal resize.
  * Screen saver mode: any key closes it.
  * Selectable color.
  * Change text scroll rate.

Package: cmatrix
Version: 2.0-1
Status: install ok installed
Priority: optional
Section: Pacstall
Maintainer: WRM-42 <y8bsbahy@anonaddy.me>
Installed-Size: unknown
Provides: cmatrix
Depends: libncurses5-dev, libncursesw5-dev
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: This is a symbolic package used by pacstall, may be removed with apt or dpkg. Terminal based The Matrix like implementation
```

The one from Ubuntu repos is version `2.0-2`, and the one by pacstall is `2.0-1`. So apt wants to update it.
