### ISSUE TITLE
Add `editor` variable to the config's settings

### ISSUE THREAD

**Issue by wizard-28** [pacstall/pacstall#468]
This `editor` variable will replace the `PACSTALL_EDITOR` environment variable.

Example:
```toml
[settings]
editor = "nvim"
```
